In [1]:
pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.4.0.tar.gz (310.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 MB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.4.0-py2.py3-none-any.whl size=311317130 sha256=df091aab7b6ec4328318d0d1c7254ed3f5fa09a76a03f7dbd4dc3790f10ebd3a
  Stored in directory: /root/.cache/pip/wheels/7b/1b/4b/3363a1d04368e7ff0d408e57ff57966fcdf00583774e761327
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.4.0

In [2]:
import pandas as pd
data = pd.read_csv('cleaned_Cric_summary.csv')

In [3]:
data = data.dropna()       # drop any rows with missing values
data

,Unnamed: 0,season,id,match_between,home_team,away_team,toss_won,decision,1st_inning_score,2nd_inning_score,...,away_overs,away_runs,away_wickets,away_boundaries,home_key_batsman,home_key_bowler,away_key_batsman,away_key_bowler,part_of_the_day,1st_inning_runs
0,0,2022,1304047,CSK v KKR,CSK,KKR,KKR,BOWL FIRST,131/5,133/4,...,18.3,133.0,4.0,15.0,"MS Dhoni,Robin Uthappa","Dwayne Bravo,Mitchell Santner","Ajinkya Rahane,Sam Billings","Umesh Yadav,Varun Chakravarthy",night,131
1,1,2022,1304048,DC v MI,DC,MI,DC,BOWL FIRST,177/5,179/6,...,20.0,177.0,5.0,24.0,"Lalit Yadav,Axar Patel","Kuldeep Yadav,Khaleel Ahmed","Ishan Kishan,Rohit Sharma","Basil Thampi,Murugan Ashwin",day/night,177
2,2,2022,1304049,PBKS v RCB,PBKS,RCB,PBKS,BOWL FIRST,205/2,208/5,...,20.0,205.0,2.0,22.0,"Bhanuka Rajapaksa,Shikhar Dhawan","Rahul Chahar,Arshdeep Singh","Faf du Plessis,Virat Kohli","Mohammed Siraj,Harshal Patel",night,205
3,3,2022,1304050,GT v LSG,GT,LSG,GT,BOWL FIRST,158/6,161/5,...,20.0,158.0,6.0,22.0,"Rahul Tewatia,Hardik Pandya","Mohammed Shami,Varun Aaron","Deepak Hooda,Ayush Badoni","Dushmantha Chameera,Krunal Pandya",night,158
4,4,2022,1304051,SRH v RR,SRH,RR,SRH,BOWL FIRST,210/6,149/7,...,20.0,210.0,6.0,30.0,"Aiden Markram,Washington Sundar","Umran Malik,T Natarajan","Sanju Samson,Devdutt Padikkal","Yuzvendra Chahal,Prasidh Krishna",night,210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,930,2008,336012,RCB v MI,RCB,MI,MI,BOWL FIRST,122/9,126/1,...,16.0,126.0,1.0,16.0,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",day/night,122
931,931,2008,336019,PBKS v RR,PBKS,RR,RR,BOWL FIRST,221/3,180/7,...,20.0,180.0,7.0,26.0,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",night,221
932,932,2008,336038,DC v RR,DC,RR,DC,BOWL FIRST,192/9,87/10,...,20.0,192.0,9.0,29.0,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",night,192
933,933,2008,336039,CSK v PBKS,CSK,PBKS,PBKS,BAT FIRST,112/8,116/1,...,20.0,112.0,8.0,13.0,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",night,112
934,934,2008,336040,CSK v RR,CSK,RR,RR,BOWL FIRST,163/5,164/7,...,20.0,164.0,7.0,17.0,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",night,163

In [4]:
# extract score and convert to integer
data['1st_inning_runs'] = data['1st_inning_score'].str.split('/').str[0].astype(int)
data['1st_inning_wkts'] = data['1st_inning_score'].str.split('/').str[1].astype(int)

data['2nd_inning_runs'] = data['2nd_inning_score'].str.split('/').str[0].astype(int)
data['2nd_inning_wkts'] = data['2nd_inning_score'].str.split('/').str[1].astype(int)

data

,Unnamed: 0,season,id,match_between,home_team,away_team,toss_won,decision,1st_inning_score,2nd_inning_score,...,away_boundaries,home_key_batsman,home_key_bowler,away_key_batsman,away_key_bowler,part_of_the_day,1st_inning_runs,1st_inning_wkts,2nd_inning_runs,2nd_inning_wkts
0,0,2022,1304047,CSK v KKR,CSK,KKR,KKR,BOWL FIRST,131/5,133/4,...,15.0,"MS Dhoni,Robin Uthappa","Dwayne Bravo,Mitchell Santner","Ajinkya Rahane,Sam Billings","Umesh Yadav,Varun Chakravarthy",night,131,5,133,4
1,1,2022,1304048,DC v MI,DC,MI,DC,BOWL FIRST,177/5,179/6,...,24.0,"Lalit Yadav,Axar Patel","Kuldeep Yadav,Khaleel Ahmed","Ishan Kishan,Rohit Sharma","Basil Thampi,Murugan Ashwin",day/night,177,5,179,6
2,2,2022,1304049,PBKS v RCB,PBKS,RCB,PBKS,BOWL FIRST,205/2,208/5,...,22.0,"Bhanuka Rajapaksa,Shikhar Dhawan","Rahul Chahar,Arshdeep Singh","Faf du Plessis,Virat Kohli","Mohammed Siraj,Harshal Patel",night,205,2,208,5
3,3,2022,1304050,GT v LSG,GT,LSG,GT,BOWL FIRST,158/6,161/5,...,22.0,"Rahul Tewatia,Hardik Pandya","Mohammed Shami,Varun Aaron","Deepak Hooda,Ayush Badoni","Dushmantha Chameera,Krunal Pandya",night,158,6,161,5
4,4,2022,1304051,SRH v RR,SRH,RR,SRH,BOWL FIRST,210/6,149/7,...,30.0,"Aiden Markram,Washington Sundar","Umran Malik,T Natarajan","Sanju Samson,Devdutt Padikkal","Yuzvendra Chahal,Prasidh Krishna",night,210,6,149,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,930,2008,336012,RCB v MI,RCB,MI,MI,BOWL FIRST,122/9,126/1,...,16.0,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",day/night,122,9,126,1
931,931,2008,336019,PBKS v RR,PBKS,RR,RR,BOWL FIRST,221/3,180/7,...,26.0,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",night,221,3,180,7
932,932,2008,336038,DC v RR,DC,RR,DC,BOWL FIRST,192/9,87/10,...,29.0,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",night,192,9,87,10
933,933,2008,336039,CSK v PBKS,CSK,PBKS,PBKS,BAT FIRST,112/8,116/1,...,13.0,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",night,112,8,116,1
934,934,2008,336040,CSK v RR,CSK,RR,RR,BOWL FIRST,163/5,164/7,...,17.0,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",night,163,5,164,7

In [5]:
data.drop(['Unnamed: 0','id','match_between','1st_inning_score','2nd_inning_score','home_score','away_score','result','part_of_the_day'], axis=1)

,season,home_team,away_team,toss_won,decision,winner,venue,home_captain,away_captain,player_of_the_match,...,away_wickets,away_boundaries,home_key_batsman,home_key_bowler,away_key_batsman,away_key_bowler,1st_inning_runs,1st_inning_wkts,2nd_inning_runs,2nd_inning_wkts
0,2022,CSK,KKR,KKR,BOWL FIRST,KKR,"Wankhede Stadium, Mumbai",Ravindra Jadeja,Shreyas Iyer,Umesh Yadav,...,4.0,15.0,"MS Dhoni,Robin Uthappa","Dwayne Bravo,Mitchell Santner","Ajinkya Rahane,Sam Billings","Umesh Yadav,Varun Chakravarthy",131,5,133,4
1,2022,DC,MI,DC,BOWL FIRST,DC,"Brabourne Stadium, Mumbai",Rishabh Pant,Rohit Sharma,Kuldeep Yadav,...,5.0,24.0,"Lalit Yadav,Axar Patel","Kuldeep Yadav,Khaleel Ahmed","Ishan Kishan,Rohit Sharma","Basil Thampi,Murugan Ashwin",177,5,179,6
2,2022,PBKS,RCB,PBKS,BOWL FIRST,PBKS,"Dr DY Patil Sports Academy, Navi Mumbai",Mayank Agarwal,Faf du Plessis,Odean Smith,...,2.0,22.0,"Bhanuka Rajapaksa,Shikhar Dhawan","Rahul Chahar,Arshdeep Singh","Faf du Plessis,Virat Kohli","Mohammed Siraj,Harshal Patel",205,2,208,5
3,2022,GT,LSG,GT,BOWL FIRST,GT,"Wankhede Stadium, Mumbai",Hardik Pandya,KL Rahul,Mohammed Shami,...,6.0,22.0,"Rahul Tewatia,Hardik Pandya","Mohammed Shami,Varun Aaron","Deepak Hooda,Ayush Badoni","Dushmantha Chameera,Krunal Pandya",158,6,161,5
4,2022,SRH,RR,SRH,BOWL FIRST,RR,"Maharashtra Cricket Association Stadium, Pune",Kane Williamson,Sanju Samson,Sanju Samson,...,6.0,30.0,"Aiden Markram,Washington Sundar","Umran Malik,T Natarajan","Sanju Samson,Devdutt Padikkal","Yuzvendra Chahal,Prasidh Krishna",210,6,149,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,2008,RCB,MI,MI,BOWL FIRST,MI,"M.Chinnaswamy Stadium, Bengaluru",Rahul Dravid,Sachin Tendulkar,Dilhara Fernando,...,1.0,16.0,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",122,9,126,1
931,2008,PBKS,RR,RR,BOWL FIRST,PBKS,"Punjab Cricket Association IS Bindra Stadium, ...",Yuvraj Singh,Shane Watson,Shaun Marsh,...,7.0,26.0,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",221,3,180,7
932,2008,DC,RR,DC,BOWL FIRST,RR,"Wankhede Stadium, Mumbai",Virender Sehwag,Shane Warne,Shane Watson,...,9.0,29.0,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",192,9,87,10
933,2008,CSK,PBKS,PBKS,BAT FIRST,CSK,"Wankhede Stadium, Mumbai",MS Dhoni,Yuvraj Singh,Makhaya Ntini,...,8.0,13.0,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",112,8,116,1
934,2008,CSK,RR,RR,BOWL FIRST,RR,"Dr DY Patil Sports Academy, Mumbai",MS Dhoni,Shane Warne,Yusuf Pathan,...,7.0,17.0,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",163,5,164,7

In [6]:
data['is_home_winner'] = (data['home_team'] == data['winner']) * 1
data

,Unnamed: 0,season,id,match_between,home_team,away_team,toss_won,decision,1st_inning_score,2nd_inning_score,...,home_key_batsman,home_key_bowler,away_key_batsman,away_key_bowler,part_of_the_day,1st_inning_runs,1st_inning_wkts,2nd_inning_runs,2nd_inning_wkts,is_home_winner
0,0,2022,1304047,CSK v KKR,CSK,KKR,KKR,BOWL FIRST,131/5,133/4,...,"MS Dhoni,Robin Uthappa","Dwayne Bravo,Mitchell Santner","Ajinkya Rahane,Sam Billings","Umesh Yadav,Varun Chakravarthy",night,131,5,133,4,0
1,1,2022,1304048,DC v MI,DC,MI,DC,BOWL FIRST,177/5,179/6,...,"Lalit Yadav,Axar Patel","Kuldeep Yadav,Khaleel Ahmed","Ishan Kishan,Rohit Sharma","Basil Thampi,Murugan Ashwin",day/night,177,5,179,6,1
2,2,2022,1304049,PBKS v RCB,PBKS,RCB,PBKS,BOWL FIRST,205/2,208/5,...,"Bhanuka Rajapaksa,Shikhar Dhawan","Rahul Chahar,Arshdeep Singh","Faf du Plessis,Virat Kohli","Mohammed Siraj,Harshal Patel",night,205,2,208,5,1
3,3,2022,1304050,GT v LSG,GT,LSG,GT,BOWL FIRST,158/6,161/5,...,"Rahul Tewatia,Hardik Pandya","Mohammed Shami,Varun Aaron","Deepak Hooda,Ayush Badoni","Dushmantha Chameera,Krunal Pandya",night,158,6,161,5,1
4,4,2022,1304051,SRH v RR,SRH,RR,SRH,BOWL FIRST,210/6,149/7,...,"Aiden Markram,Washington Sundar","Umran Malik,T Natarajan","Sanju Samson,Devdutt Padikkal","Yuzvendra Chahal,Prasidh Krishna",night,210,6,149,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,930,2008,336012,RCB v MI,RCB,MI,MI,BOWL FIRST,122/9,126/1,...,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",day/night,122,9,126,1,0
931,931,2008,336019,PBKS v RR,PBKS,RR,RR,BOWL FIRST,221/3,180/7,...,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",night,221,3,180,7,1
932,932,2008,336038,DC v RR,DC,RR,DC,BOWL FIRST,192/9,87/10,...,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",night,192,9,87,10,0
933,933,2008,336039,CSK v PBKS,CSK,PBKS,PBKS,BAT FIRST,112/8,116/1,...,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",night,112,8,116,1,1
934,934,2008,336040,CSK v RR,CSK,RR,RR,BOWL FIRST,163/5,164/7,...,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",night,163,5,164,7,0

In [7]:
from sklearn.preprocessing import LabelEncoder         # import label encoder from sklearn for encoding categorical data, and select the columns to encode

labelEnc = LabelEncoder()
colsForEncoding = ['home_team', 'away_team', 'toss_won', 'decision', 'venue', 'home_captain', 'away_captain', 'player_of_the_match','home_key_batsman','home_key_bowler','away_key_batsman','away_key_bowler']
for i in colsForEncoding:                              # iterate through the columns and encode the categorical data using label encoding
    data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])

<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])
<ipython-input-7-72f043c5d9cd>:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.loc[:, i] = labelEnc.fit_transform(data.loc[:, i])

In [8]:
data

,Unnamed: 0,season,id,match_between,home_team,away_team,toss_won,decision,1st_inning_score,2nd_inning_score,...,home_key_batsman,home_key_bowler,away_key_batsman,away_key_bowler,part_of_the_day,1st_inning_runs,1st_inning_wkts,2nd_inning_runs,2nd_inning_wkts,is_home_winner
0,0,2022,1304047,CSK v KKR,0,4,4,1,131/5,133/4,...,328,188,38,737,night,131,5,133,4,0
1,1,2022,1304048,DC v MI,1,7,1,1,177/5,179/6,...,311,325,253,99,day/night,177,5,179,6,1
2,2,2022,1304049,PBKS v RCB,8,10,8,1,205/2,208/5,...,72,515,218,437,night,205,2,208,5,1
3,3,2022,1304050,GT v LSG,3,6,3,1,158/6,161/5,...,442,388,166,195,night,158,6,161,5,1
4,4,2022,1304051,SRH v RR,13,12,13,1,210/6,149/7,...,32,730,576,797,night,210,6,149,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,930,2008,336012,RCB v MI,10,7,7,1,122/9,126/1,...,90,145,573,186,day/night,122,9,126,1,0
931,931,2008,336019,PBKS v RR,8,12,12,1,221/3,180/7,...,559,475,440,654,night,221,3,180,7,1
932,932,2008,336038,DC v RR,1,12,1,1,192/9,87/10,...,661,195,604,651,night,192,9,87,10,0
933,933,2008,336039,CSK v PBKS,0,8,8,0,112/8,116/1,...,645,357,494,260,night,112,8,116,1,1
934,934,2008,336040,CSK v RR,0,12,12,1,163/5,164/7,...,645,8,739,786,night,163,5,164,7,0

In [9]:
from pyspark.sql import SparkSession                   # import spark and create a spark session, then convert the pandas dataframe to spark dataframe
spark = SparkSession.builder.appName("CricPrediction").getOrCreate()
df = spark.createDataFrame(data)

In [10]:
df = df.drop('Unnamed: 0','id','1st_inning_score','2nd_inning_score','home_score','away_score','result','part_of_the_day')
df.show()

+------+-------------+---------+---------+--------+--------+------+-----+------------+------------+-------------------+----------+----------+---------+------------+---------------+----------+---------+------------+---------------+----------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+--------------+
|season|match_between|home_team|away_team|toss_won|decision|winner|venue|home_captain|away_captain|player_of_the_match|super_over|home_overs|home_runs|home_wickets|home_boundaries|away_overs|away_runs|away_wickets|away_boundaries|home_key_batsman|home_key_bowler|away_key_batsman|away_key_bowler|1st_inning_runs|1st_inning_wkts|2nd_inning_runs|2nd_inning_wkts|is_home_winner|
+------+-------------+---------+---------+--------+--------+------+-----+------------+------------+-------------------+----------+----------+---------+------------+---------------+----------+---------+------------+---------------+----------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+--------------+
|  2022|    CSK v KKR|        0|        4|       4|       1|   KKR|   34|          36|          48|                243|     false|      20.0|    131.0|         5.0|           15.0|      18.3|    133.0|         4.0|           15.0|             328|            188|              38|            737|            131|              5|            133|              4|             0|
|  2022|      DC v MI|        1|        7|       1|       1|    DC|    2|          38|          40|                113|     false|      18.2|    179.0|         6.0|           25.0|      20.0|    177.0|         5.0|           24.0|             311|            325|             253|             99|            177|              5|            179|              6|             1|
|  2022|   PBKS v RCB|        8|       10|       8|       1|  PBKS|    6|          31|          16|                163|     false|      19.0|    208.0|         5.0|           25.0|      20.0|    205.0|         2.0|           22.0|              72|            515|             218|            437|            205|              2|            208|              5|             1|
|  2022|     GT v LSG|        3|        6|       3|       1|    GT|   34|          20|          24|                145|     false|      19.4|    161.0|         5.0|           23.0|      20.0|    158.0|         6.0|           22.0|             442|            388|             166|            195|            158|              6|            161|              5|             1|
|  2022|     SRH v RR|       13|       12|      13|       1|    RR|   17|          23|          43|                205|     false|      20.0|    149.0|         7.0|           17.0|      20.0|    210.0|         6.0|           30.0|              32|            730|             576|            797|            210|              6|            149|              7|             0|
|  2022|    RCB v KKR|       10|        4|      10|       1|   RCB|    6|          15|          48|                251|     false|      19.2|    132.0|         7.0|           16.0|      18.5|    128.0|        10.0|           18.0|             565|            751|              70|            715|            128|             10|            132|              7|             1|
|  2022|    LSG v CSK|        6|        0|       6|       1|   LSG|    2|          22|          37|                 63|     false|      19.3|    211.0|         4.0|           27.0|      20.0|    210.0|         7.0|           32.0|             426|            553|             529|            196|            210|              7|            211|              4|             1|
|  2022|   KKR v PBKS|        4|        8|       4|       1|   KKR|   34|          46|          32|                243|     false|      14.3|    141.0|         4.0|           20.0|      18.2|    137.0|        10.0|           19.0|              57|            727|              92|            543|            137|             10|            141|              4|             1|
|  2022|      MI v RR|        7|       12|       7|       1|    RR|    6|          39|          43|                 98|     false|      20.0|    170.0|         8.0|           21.0|      20.0|    193.0|         8.0|           28.0|             657|            270|             296|            795|            193|              8|            170|              8|             0|
|  2022|      GT v DC|        3|        1|       1|       1|    GT|   17|          20|          39|                120|     false|      20.0|    171.0|         6.0|           19.0|      20.0|    157.0|         9.0|           21.0|             606|            349|             510|            478|            171|              6|            157|              9|             1|
|  2022|   CSK v PBKS|        0|        8|       0|       1|  PBKS|    2|          36|          32|                119|     false|      18.0|    126.0|        10.0|           16.0|      20.0|    180.0|         8.0|           23.0|             588|            129|             351|            546|            180|              8|            126|             10|             0|
|  2022|    SRH v LSG|       13|        6|      13|       1|   LSG|    6|          23|          24|                 25|     false|      20.0|    157.0|         9.0|           17.0|      20.0|    169.0|         7.0|           20.0|             446|            704|             303|             86|            169|              7|            157|              9|             0|
|  2022|     RR v RCB|       12|       10|      10|       1|   RCB|   34|          41|          16|                 58|     false|      20.0|    169.0|         3.0|           17.0|      19.1|    173.0|         6.0|           25.0|             262|            781|             590|            237|            169|              3|            173|              6|             0|
|  2022|     KKR v MI|        4|        7|       4|       1|   KKR|   17|          46|          40|                165|     false|      16.0|    162.0|         5.0|           24.0|      20.0|    161.0|         4.0|           20.0|             415|            464|             677|            474|            161|              4|            162|              5|             1|
|  2022|     LSG v DC|        6|        1|       6|       1|   LSG|    6|          22|          39|                176|     false|      19.4|    155.0|         4.0|           16.0|      20.0|    149.0|         3.0|           19.0|             430|            555|             461|            378|            149|              3|            155|              4|             1|
|  2022|    PBKS v GT|        8|        3|       3|       1|    GT|    2|          31|          21|                223|     false|      20.0|    189.0|         9.0|           27.0|      20.0|    190.0|         4.0|           26.0|             317|            293|             645|            566|            189|              9|            190|              4|             0|
|  2022|    CSK v SRH|        0|       13|      13|       1|   SRH|    6|          36|          25|                  3|     false|      20.0|    154.0|         7.0|           17.0|      17.4|    155.0|         2.0|           19.0|             378|            417|              22|            773|            154|              7|            155|              2|             0|
|  2022|     RCB v MI|       10|        7|      10|       1|   RCB|   17|          15|          40|                 22|     false|      18.3|    152.0|         3.0|           17.0|      20.0|    151.0|         6.0|           21.0|              65|            225|             673|            304|            151|              6|            152|              3|             1|
|  2022|     KKR v DC|        4|        1|       4|       1|    DC|    2|          46|          39|                113|     false|      19.4|    171.0|        10.0|           22.0|      20.0|    215.0|         5.0|           29.0|             596|            683|             159|            377|            215|              5|            171|             10|             0|
|  2022|     RR v LSG|       12|        6|       6|       1|    RR|   34|          41|          24|                257|     false|      20.0|    165.0|         6.0|           19.0|      20.0|    162.0|         8.0|           19.0|             586|            781|             468|            369|            165|              6|            162|              8|             1|
+------+-------------+---------+---------+--------+--------+------+-----+------------+------------+-------------------+----------+----------+---------+------------+---------------+----------+---------+------------+---------------+----------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+--------------+
only showing top 20 rows

In [11]:
from pyspark.sql.functions import col, avg

# Run rate of each team
df = df.withColumn('home_run_rate', col('home_runs')/col('home_overs'))
df = df.withColumn('away_run_rate', col('away_runs')/col('away_overs'))

# Economy rate of each team
df = df.withColumn('home_economy_rate', col('away_runs')/col('home_overs'))
df = df.withColumn('away_economy_rate', col('home_runs')/col('away_overs'))


# The difference between the scores of each team in the 1st inning and 2nd inning
df = df.withColumn('score_difference', col('home_runs') - col('away_runs'))

# The difference between the number of wickets taken by each team in the 1st inning and 2nd inning
df = df.withColumn('wicket_difference', col('home_wickets') - col('away_wickets'))


df.show()

+------+-------------+---------+---------+--------+--------+------+-----+------------+------------+-------------------+----------+----------+---------+------------+---------------+----------+---------+------------+---------------+----------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+--------------+------------------+-----------------+------------------+-----------------+----------------+-----------------+
|season|match_between|home_team|away_team|toss_won|decision|winner|venue|home_captain|away_captain|player_of_the_match|super_over|home_overs|home_runs|home_wickets|home_boundaries|away_overs|away_runs|away_wickets|away_boundaries|home_key_batsman|home_key_bowler|away_key_batsman|away_key_bowler|1st_inning_runs|1st_inning_wkts|2nd_inning_runs|2nd_inning_wkts|is_home_winner|     home_run_rate|    away_run_rate| home_economy_rate|away_economy_rate|score_difference|wicket_difference|
+------+-------------+---------+---------+--------+--------+------+-----+------------+------------+-------------------+----------+----------+---------+------------+---------------+----------+---------+------------+---------------+----------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+--------------+------------------+-----------------+------------------+-----------------+----------------+-----------------+
|  2022|    CSK v KKR|        0|        4|       4|       1|   KKR|   34|          36|          48|                243|     false|      20.0|    131.0|         5.0|           15.0|      18.3|    133.0|         4.0|           15.0|             328|            188|              38|            737|            131|              5|            133|              4|             0|              6.55| 7.26775956284153|              6.65|7.158469945355191|            -2.0|              1.0|
|  2022|      DC v MI|        1|        7|       1|       1|    DC|    2|          38|          40|                113|     false|      18.2|    179.0|         6.0|           25.0|      20.0|    177.0|         5.0|           24.0|             311|            325|             253|             99|            177|              5|            179|              6|             1| 9.835164835164836|             8.85| 9.725274725274726|             8.95|             2.0|              1.0|
|  2022|   PBKS v RCB|        8|       10|       8|       1|  PBKS|    6|          31|          16|                163|     false|      19.0|    208.0|         5.0|           25.0|      20.0|    205.0|         2.0|           22.0|              72|            515|             218|            437|            205|              2|            208|              5|             1|10.947368421052632|            10.25|10.789473684210526|             10.4|             3.0|              3.0|
|  2022|     GT v LSG|        3|        6|       3|       1|    GT|   34|          20|          24|                145|     false|      19.4|    161.0|         5.0|           23.0|      20.0|    158.0|         6.0|           22.0|             442|            388|             166|            195|            158|              6|            161|              5|             1|  8.29896907216495|              7.9| 8.144329896907218|             8.05|             3.0|             -1.0|
|  2022|     SRH v RR|       13|       12|      13|       1|    RR|   17|          23|          43|                205|     false|      20.0|    149.0|         7.0|           17.0|      20.0|    210.0|         6.0|           30.0|              32|            730|             576|            797|            210|              6|            149|              7|             0|              7.45|             10.5|              10.5|             7.45|           -61.0|              1.0|
|  2022|    RCB v KKR|       10|        4|      10|       1|   RCB|    6|          15|          48|                251|     false|      19.2|    132.0|         7.0|           16.0|      18.5|    128.0|        10.0|           18.0|             565|            751|              70|            715|            128|             10|            132|              7|             1|             6.875|6.918918918918919| 6.666666666666667|7.135135135135135|             4.0|             -3.0|
|  2022|    LSG v CSK|        6|        0|       6|       1|   LSG|    2|          22|          37|                 63|     false|      19.3|    211.0|         4.0|           27.0|      20.0|    210.0|         7.0|           32.0|             426|            553|             529|            196|            210|              7|            211|              4|             1|10.932642487046632|             10.5|10.880829015544041|            10.55|             1.0|             -3.0|
|  2022|   KKR v PBKS|        4|        8|       4|       1|   KKR|   34|          46|          32|                243|     false|      14.3|    141.0|         4.0|           20.0|      18.2|    137.0|        10.0|           19.0|              57|            727|              92|            543|            137|             10|            141|              4|             1|  9.86013986013986|7.527472527472527|  9.58041958041958|7.747252747252747|             4.0|             -6.0|
|  2022|      MI v RR|        7|       12|       7|       1|    RR|    6|          39|          43|                 98|     false|      20.0|    170.0|         8.0|           21.0|      20.0|    193.0|         8.0|           28.0|             657|            270|             296|            795|            193|              8|            170|              8|             0|               8.5|             9.65|              9.65|              8.5|           -23.0|              0.0|
|  2022|      GT v DC|        3|        1|       1|       1|    GT|   17|          20|          39|                120|     false|      20.0|    171.0|         6.0|           19.0|      20.0|    157.0|         9.0|           21.0|             606|            349|             510|            478|            171|              6|            157|              9|             1|              8.55|             7.85|              7.85|             8.55|            14.0|             -3.0|
|  2022|   CSK v PBKS|        0|        8|       0|       1|  PBKS|    2|          36|          32|                119|     false|      18.0|    126.0|        10.0|           16.0|      20.0|    180.0|         8.0|           23.0|             588|            129|             351|            546|            180|              8|            126|             10|             0|               7.0|              9.0|              10.0|              6.3|           -54.0|              2.0|
|  2022|    SRH v LSG|       13|        6|      13|       1|   LSG|    6|          23|          24|                 25|     false|      20.0|    157.0|         9.0|           17.0|      20.0|    169.0|         7.0|           20.0|             446|            704|             303|             86|            169|              7|            157|              9|             0|              7.85|             8.45|              8.45|             7.85|           -12.0|              2.0|
|  2022|     RR v RCB|       12|       10|      10|       1|   RCB|   34|          41|          16|                 58|     false|      20.0|    169.0|         3.0|           17.0|      19.1|    173.0|         6.0|           25.0|             262|            781|             590|            237|            169|              3|            173|              6|             0|              8.45|9.057591623036648|              8.65|8.848167539267015|            -4.0|             -3.0|
|  2022|     KKR v MI|        4|        7|       4|       1|   KKR|   17|          46|          40|                165|     false|      16.0|    162.0|         5.0|           24.0|      20.0|    161.0|         4.0|           20.0|             415|            464|             677|            474|            161|              4|            162|              5|             1|            10.125|             8.05|           10.0625|              8.1|             1.0|              1.0|
|  2022|     LSG v DC|        6|        1|       6|       1|   LSG|    6|          22|          39|                176|     false|      19.4|    155.0|         4.0|           16.0|      20.0|    149.0|         3.0|           19.0|             430|            555|             461|            378|            149|              3|            155|              4|             1|7.9896907216494855|             7.45| 7.680412371134021|             7.75|             6.0|              1.0|
|  2022|    PBKS v GT|        8|        3|       3|       1|    GT|    2|          31|          21|                223|     false|      20.0|    189.0|         9.0|           27.0|      20.0|    190.0|         4.0|           26.0|             317|            293|             645|            566|            189|              9|            190|              4|             0|              9.45|              9.5|               9.5|             9.45|            -1.0|              5.0|
|  2022|    CSK v SRH|        0|       13|      13|       1|   SRH|    6|          36|          25|                  3|     false|      20.0|    154.0|         7.0|           17.0|      17.4|    155.0|         2.0|           19.0|             378|            417|              22|            773|            154|              7|            155|              2|             0|               7.7|8.908045977011495|              7.75| 8.85057471264368|            -1.0|              5.0|
|  2022|     RCB v MI|       10|        7|      10|       1|   RCB|   17|          15|          40|                 22|     false|      18.3|    152.0|         3.0|           17.0|      20.0|    151.0|         6.0|           21.0|              65|            225|             673|            304|            151|              6|            152|              3|             1| 8.306010928961749|             7.55| 8.251366120218579|              7.6|             1.0|             -3.0|
|  2022|     KKR v DC|        4|        1|       4|       1|    DC|    2|          46|          39|                113|     false|      19.4|    171.0|        10.0|           22.0|      20.0|    215.0|         5.0|           29.0|             596|            683|             159|            377|            215|              5|            171|             10|             0| 8.814432989690722|            10.75|11.082474226804125|             8.55|           -44.0|              5.0|
|  2022|     RR v LSG|       12|        6|       6|       1|    RR|   34|          41|          24|                257|     false|      20.0|    165.0|         6.0|           19.0|      20.0|    162.0|         8.0|           19.0|             586|            781|             468|            369|            165|              6|            162|              8|             1|              8.25|              8.1|               8.1|             8.25|             3.0|             -2.0|
+------+-------------+---------+---------+--------+--------+------+-----+------------+------------+-------------------+----------+----------+---------+------------+---------------+----------+---------+------------+---------------+----------------+---------------+----------------+---------------+---------------+---------------+---------------+---------------+--------------+------------------+-----------------+------------------+-----------------+----------------+-----------------+
only showing top 20 rows

In [12]:
from pyspark.ml.feature import VectorAssembler, StringIndexer

# Define the feature columns
featuresCol = ['home_team','away_team','toss_won','decision', 'venue','home_captain','away_captain','player_of_the_match','home_overs','home_runs','home_wickets','home_boundaries','away_overs','away_runs','away_wickets','away_boundaries','1st_inning_runs','1st_inning_wkts','2nd_inning_runs','2nd_inning_wkts','home_run_rate','away_run_rate','home_economy_rate','away_economy_rate','score_difference','wicket_difference']

# Assemble the features into a single vector column
#Creating a VectorAssembler object assemble that will assemble the feature columns defined above into a single vector column called 'features'.

assemble = VectorAssembler(inputCols=featuresCol, outputCol='features')

df = assemble.transform(df)
indexer = StringIndexer(inputCol="is_home_winner", outputCol="label")
df = indexer.fit(df).transform(df)

label_col = 'label'
df = df.select(['features', label_col])

In [13]:
train, test = df.randomSplit([0.7, 0.3], seed=123)

In [14]:
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

rf = RandomForestClassifier(numTrees=100, maxDepth=4, labelCol=label_col, seed=123)
rf_model = rf.fit(train)

In [15]:
rf_predictions = rf_model.transform(test)
# Compute evaluation metrics such as accuracy, precision, recall, F1-score, etc.
rf_evaluator = MulticlassClassificationEvaluator(labelCol=label_col, metricName="accuracy")
rf_accuracy = rf_evaluator.evaluate(rf_predictions)
rf_precision = rf_evaluator.evaluate(rf_predictions, {rf_evaluator.metricName: "weightedPrecision"})
rf_recall = rf_evaluator.evaluate(rf_predictions, {rf_evaluator.metricName: "weightedRecall"})
rf_f1 = rf_evaluator.evaluate(rf_predictions, {rf_evaluator.metricName: "f1"})

# Print the evaluation metrics
print("Accuracy: %g" % rf_accuracy)
print("Precision: %g" % rf_precision)
print("Recall: %g" % rf_recall)
print("F1-score: %g" % rf_f1)

Accuracy: 0.98893
Precision: 0.989147
Recall: 0.98893
F1-score: 0.988915

In [16]:
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator

# Create a ParamGridBuilder with hyperparameters to try
param_grid = (ParamGridBuilder()
             .addGrid(rf.numTrees, [50, 100, 150])
             .addGrid(rf.maxDepth, [2, 4, 6])
             .build())

# Create a CrossValidator with the Random Forest Classifier and ParamGridBuilder
cv = CrossValidator(estimator=rf, estimatorParamMaps=param_grid, evaluator=rf_evaluator, numFolds=5, seed=123)

# Fit the CrossValidator to the training data
cv_model = cv.fit(train)

# Get the best model from the CrossValidator
best_model = cv_model.bestModel

predictions = best_model.transform(test)
# Compute evaluation metrics such as accuracy, precision, recall, F1-score, etc.
rft_evaluator = MulticlassClassificationEvaluator(labelCol=label_col, metricName="accuracy")
rft_accuracy = rft_evaluator.evaluate(predictions)
rft_precision = rft_evaluator.evaluate(predictions, {rft_evaluator.metricName: "weightedPrecision"})
rft_recall = rft_evaluator.evaluate(predictions, {rft_evaluator.metricName: "weightedRecall"})
rft_f1 = rft_evaluator.evaluate(predictions, {rft_evaluator.metricName: "f1"})

# Print the evaluation metrics
print("Accuracy: %g" % rft_accuracy)
print("Precision: %g" % rft_precision)
print("Recall: %g" % rft_recall)
print("F1-score: %g" % rft_f1)

Accuracy: 0.98524
Precision: 0.985323
Recall: 0.98524
F1-score: 0.985227

In [17]:
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# Split the data into training and test sets
train, test = df.randomSplit([0.7, 0.3], seed=123)

# Create a LogisticRegression object and fit the model to the training data
lr = LogisticRegression(labelCol=label_col, featuresCol="features", maxIter=10, regParam=0.01)
lr_model = lr.fit(train)

# Use the model to make predictions on the test data
lr_predictions = lr_model.transform(test)

# Compute evaluation metrics such as accuracy, precision, recall, F1-score, etc.
lr_evaluator = MulticlassClassificationEvaluator(labelCol=label_col, metricName="accuracy")
lr_accuracy = lr_evaluator.evaluate(lr_predictions)
lr_precision = lr_evaluator.evaluate(lr_predictions, {lr_evaluator.metricName: "weightedPrecision"})
lr_recall = lr_evaluator.evaluate(lr_predictions, {lr_evaluator.metricName: "weightedRecall"})
lr_f1 = lr_evaluator.evaluate(lr_predictions, {lr_evaluator.metricName: "f1"})

# Print the evaluation metrics
print("Accuracy: %g" % lr_accuracy)
print("Precision: %g" % lr_precision)
print("Recall: %g" % lr_recall)
print("F1-score: %g" % lr_f1)

Accuracy: 0.937269
Precision: 0.938799
Recall: 0.937269
F1-score: 0.936971

In [20]:
from pyspark.ml.classification import LinearSVC
from pyspark.ml.evaluation import MulticlassClassificationEvaluator


# Split the data into training and test sets
train, test = df.randomSplit([0.7, 0.3], seed=123)

svm = LinearSVC(labelCol=label_col, featuresCol="features", maxIter=10, regParam=0.1)

# Define the evaluator
svm_evaluator = MulticlassClassificationEvaluator(predictionCol='prediction', labelCol='label', metricName='accuracy')

# Define the parameter grid
paramGrid = (ParamGridBuilder()
             .addGrid(svm.regParam, [0.1, 0.01])
             .addGrid(svm.maxIter, [10, 20])
             .build())

# Define the cross validator
cv = CrossValidator(estimator=svm, estimatorParamMaps=paramGrid, evaluator=svm_evaluator, numFolds=5)

# Fit the cross validator to the train data
svm_model = cv.fit(train)

# Make predictions on the test data
svm_predictions = svm_model.transform(test)
svm_evaluator = MulticlassClassificationEvaluator(labelCol=label_col, metricName="accuracy")


# Evaluate the model performance using the evaluation metric
gbt_accuracy = svm_evaluator.evaluate(svm_predictions)
gbt_precision = svm_evaluator.evaluate(svm_predictions, {svm_evaluator.metricName: "weightedPrecision"})
gbt_recall = svm_evaluator.evaluate(svm_predictions, {svm_evaluator.metricName: "weightedRecall"})
gbt_f1 = svm_evaluator.evaluate(svm_predictions, {svm_evaluator.metricName: "f1"})

# Print the evaluation metrics
print("Accuracy: %g" % gbt_accuracy)
print("Precision: %g" % gbt_precision)
print("Recall: %g" % gbt_recall)
print("F1-score: %g" % gbt_f1)

Accuracy: 0.9631
Precision: 0.963392
Recall: 0.9631
F1-score: 0.963032

In [19]:
from pyspark.ml.classification import GBTClassifier

train, test = df.randomSplit([0.7, 0.3], seed=123)

# Initialize the Gradient Boosting classifier
gbt = GBTClassifier(labelCol=label_col, featuresCol="features", maxIter=10)

# Define the hyperparameter grid to search
param_grid = ParamGridBuilder() \
    .addGrid(gbt.maxDepth, [2, 4, 6]) \
    .addGrid(gbt.stepSize, [0.05, 0.1, 0.2]) \
    .build()

# Define the evaluation metric
gbt_evaluator = MulticlassClassificationEvaluator(labelCol=label_col, metricName="accuracy")

# Define the cross-validation object
gbt_cv = CrossValidator(estimator=gbt, estimatorParamMaps=param_grid, evaluator=gbt_evaluator, numFolds=5)

# Fit the model using the cross-validation object
gbt_model = gbt_cv.fit(train)

# Make predictions on the test set
gbt_predictions = gbt_model.transform(test)

# Evaluate the model performance using the evaluation metric
gbt_accuracy = gbt_evaluator.evaluate(gbt_predictions)
gbt_precision = gbt_evaluator.evaluate(gbt_predictions, {gbt_evaluator.metricName: "weightedPrecision"})
gbt_recall = gbt_evaluator.evaluate(gbt_predictions, {gbt_evaluator.metricName: "weightedRecall"})
gbt_f1 = gbt_evaluator.evaluate(gbt_predictions, {gbt_evaluator.metricName: "f1"})

# Print the evaluation metrics
print("Accuracy: %g" % gbt_accuracy)
print("Precision: %g" % gbt_precision)
print("Recall: %g" % gbt_recall)
print("F1-score: %g" % gbt_f1)

Accuracy: 0.97417
Precision: 0.974344
Recall: 0.97417
F1-score: 0.974135